### PR TITLE
20170513 Fix + Speedup: Defining Rectangles

### PR DESCRIPTION
**Pull request by HENDRIX-ZT2**
I like the new rectangle code, seems to be a good speedup!

However, I think  "If coordX >= coordA.X And coordX < coordB.X Then" can never be true. It works for Y. If we split it into two loops, we can make use of that condition. First Loop as it is, getting left, top and bottom.
Second loop would swap "While coordX" and "While coordY" from the first loop, and only check the area that the other loop had not covered to get the right coord.

I think "If IsNothing(curColor) = True And curColor.A <> 255 Then ...End If" is redundant, because it does the exact same two lines above without condidtions? 

I had this idea before reading through your new code:
"how about we split the while loops into four ones And break out of each as soon as we find a non-transparent pixel?
go over each line from the top -> get coordA.Y
go over each column from the left -> get coordA.X
go over each line from the bottom -> get coordB.Y
go over each column from the right -> get coordB.X
that would speed things up in cases where there is relatively little padding on each side, but a large defining rectangle"

My new idea is a hybrid of that and your new code, and it runs a tiny bit faster (I timed both your new one and my new one) and produces better results

See this for the difference in output and a visual explanation of my new algorithm:
bug

This time I made sure not to change the line endings, but still the git difference doesn't work... <.< Anyway I've only changed bitmap_getDefiningRectangle so it's easy enough to compare.

### CODE REVIEW

**Comment by jbostoen** [comment]
Seems like we're focussing on the exact same thing right now, I just committed my latest version of the code and spotted the same bottle neck (this function). To test if I don't break anything, I'm using a slimmed down version of Vondell's Red Panda (keeping all the animations except for the young); and see if I can convert ZT1 <=> PNG.

I'll take a look at your logic.

**Comment by jbostoen** [comment]
Can't we do better?

First find out A. Then find B and skip quite some stuff.
untitled

**Comment by jbostoen** [comment]
You're right, it's incorrect, it should be red.
untitled

Then it's just still the same as your idea.

**Comment by HENDRIX-ZT2** [comment]
Yeah I don't think we can avoid checking the complete outer area. My code only checks each outside pixel once so I see little potential for improval there. Maybe we can write cleaner code but the basic idea would largely remain the same.

Perhaps we could optimize it with an array operation (build a 1bit array for the image: transparent vs. opaque), but I don't think that'd give us a significant boost. It would probably be slower because we'd have to query every single pixel to build that array...

**Comment by jbostoen** [comment]
Maybe there's some sort of native crop function which could do this, but I haven't found it yet.

**Comment by HENDRIX-ZT2** [comment]
I doubt there is a built-in solution for our problem. It's not _that_ trivial I think.

**Comment by jbostoen** [comment]
- code in masterbranch updated, used your code.
- also changed a lot of the command line stuff. It's longer, but makes more sense now.

I hope we can still find a faster way to determine this rectangle, but I haven't found anything yet to get rid of the transparent border in a faster way. 

It's a matter of patience though, but if you export .PNGs and keep the canvas size and then convert them to ZT1 again, it's really slow. Maybe it does stuff twice too at some point. Needs investigation.

**Comment by HENDRIX-ZT2** [comment]
"export .PNGs and keep the canvas size and then convert them to ZT1 again, it's really slow"

Is the PNG export palettized or full color? That seems the most likely culprit to me.

**Comment by jbostoen** [comment]
Export from ZT1 to PNG: fast. Just puts the frame's (already cropped) content on the big canvas.
Import from PNG to ZT1: slow. it's a 512x512 image. To properly write the frame according to ZT1 standards (we could cheat a little there but it's been my intent to match the original approach as closely as possible), we need to get the 'defining rectangle' first. 

Then once we got that, the image is cropped and a later point it's also processed pixel by pixel to lookup the color.

**Comment by HENDRIX-ZT2** [comment]
Ah, I see. 512 px is a lot. No wonder it is slow haha.

We could have it automatically determine the required frame size for each ZT1 graphic. That's how I do it in my blender script. I check the dimensions of the model, take the largest dimension at frame 0 and then make sure the image is twice (or 2.5 times or whatever you need) as big. No need to waste huge images on tiny sprites. Just use as much as you need to capture everything + some tolerance. This is similar to your "crop to largest frame" method. Is there any reason why each graphic would need the same size? As long as each frame of a graphic has the same size, you can always reconstruct the original completely.

Or, we could start from the center and see when we no longer have an opaque pixel on every edge of a growing rectangle. I think that would be reasonably fast even for large canvases. But then it becomes problematic when the opaque stuff is not contiguous. Think of the bigfoot throwing a stone -> you would lose the stone.

**Comment by jbostoen** [comment]
No need it's that big, it was just to settle on one canvas size. Additional benefit: if you indeed export and import again; no steps are necessary for offsetting/rotation fixing.

The canvas size was chosen to be able to support (nearly?) any ZT1 graphic.

Guess we mostly need patience though, but would still be great if we could make it more efficient somehow.

**Comment by HENDRIX-ZT2** [comment]
Why? You can easily calculate the necessary dimensions in "world space" from the world space offset and the image size in "image space" to prevent messing up the offset. The only thing you have to do is make sure the origin remains in the center of the exported image sequence.

See this explanation:
offset
x is the origin
red arrow denotes the offset
black border marks the cropped dimensions
green lines are just helpers
blue border is the required size for export

No need for rotation fixing if you do it like that

**Comment by jbostoen** [comment]
OK, that could be added as an extra option too. 
I'd still like to keep the 512x512 pngs as well though.

**Comment by HENDRIX-ZT2** [comment]
But what's the practical use of that? The huge blank area just slows down things incredibly. I really can't think of any scenario where 512 px would be better than "centered relative to the origin"?

**Comment by jbostoen** [comment]
I think I have a better idea. But we'll need to see if it works out speed-wise. It has the benefit of not needing to go over every other aspect of the image.

The idea: checking whole areas at once to see if they contain more than 1 (transparent) color. 
A crop would be performed each time (= native function in VB.NET, so might be faster).

If so: process. 
If not: skip. 

The area could simply be a pixel row or column. 

-
The concept to find the most left pixel could be: 
* divide entire canvas in 2.
* if left side only contains 1 color: skip and go for second part. Divide and see.
* if left side contains more than 1 color: there's a relevant pixel. Divide again. 
* if left side contains more than 1 color AND is only 1px wide: this is the most left pixel.

Same principle could be used to determine most right pixel; most top; most bottom. 
If the cropping and counting colors is faster, this should be a significant speed up for larger images. 
For smaller images with almost no cropping, it could be a bit slower, but the impact would not be significant.

**Comment by HENDRIX-ZT2** [comment]
Recursive can be good but I fear we need to do many iterations to find the right pixel. Is checking the color palette significantly faster, ie. is there a value you don't have to loop over? Because if you have to loop again, you I doubt there will be much benefit.
Oh and why do you think native VB functions will be faster than our code? We're not writing in python but it is compiled just the same, so I don't understand where they could have a significant speed advantage?

I'll try and implement that "center around origin" method now.

**Comment by jbostoen** [comment]
Counting colors seems to be done by going over them in most examples I've seen so far.

Maybe a quick color remapping ( https://msdn.microsoft.com/en-us/library/4b4dc1kz.aspx?cs-save-lang=1&cs-lang=vb#code-snippet-1 ) and comparing the graphics is an alternative method; but we'd need to see if it's faster or not.

**Comment by HENDRIX-ZT2** [comment]
I really can't see this being any faster - we'd have to go over many pixels more than once to make the recursive determination work.

**Comment by jbostoen** [comment]
The idea is: *if* color replacement is faster and we can compare images: we can scan a lot more pixels at once.

**Comment by jbostoen** [comment]
I might have spotted something:
* http://www.dreamincode.net/forums/topic/169932-something-faster-than-bitmapgetpixel/
* https://www.codeproject.com/Articles/617613/Fast-pixel-operations-in-NET-with-and-without-unsa

Will look at implementing this sometime soon.

**Comment by HENDRIX-ZT2** [comment]
That seems like a cool approach! I don't have time to code anytime soon, but I suspect the performance gain compared to the get and setPixel methods is due to avoiding updates of the whole data after each edit. If you change the data using the new method, you only do one refresh in the end.

**Comment by jbostoen** [comment]
Try it, it's implemented, seemed lots faster. 

I left the old function in as well for now, but it seems to work correctly.

**Pull request closed without merging**
